- name: Creating a directory.
  tags: directory
  file:
    path: ~/prometheus
    state: directory

- name: Downloading Prometheus and extracting its files.
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.39.1/prometheus-2.39.1.linux-amd64.tar.gz
    dest: ~/prometheus
    remote_src: yes
    mode: 0777
    owner: root
    group: root

- name: Adding the Prometheus executables to a PATH.
  tags: executables
  shell: |
    cd ~/prometheus/prometheus*
    cp -r . /usr/local/bin/prometheus
- name: Copying the Prometheus service file.
  tags: servicefile
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 777

- name: Starteing and enabled the httpd.
  tags: serviceon
  service:
    name: prometheus
    state: restarted
    enabled: true
